const languages = [
  { name: "Afrikaans", code: "af", direction: "ltr", shortCode: "za" },
  { name: "Albanian", code: "sq", direction: "ltr", shortCode: "al" },
  { name: "Amharic", code: "am", direction: "ltr", shortCode: "et" },
  { name: "Arabic", code: "ar", direction: "rtl", shortCode: "ae" },
  { name: "Armenian", code: "hy", direction: "ltr", shortCode: "am" },
  { name: "Azerbaijani", code: "az", direction: "ltr", shortCode: "az" },
  { name: "Basque", code: "eu", direction: "ltr", shortCode: "es" },
  { name: "Belarusian", code: "be", direction: "ltr", shortCode: "by" },
  { name: "Bengali", code: "bn", direction: "ltr", shortCode: "bd" },
  { name: "Bosnian", code: "bs", direction: "ltr", shortCode: "ba" },
  { name: "Bulgarian", code: "bg", direction: "ltr", shortCode: "bg" },
  { name: "Catalan", code: "ca", direction: "ltr", shortCode: "es" },
  { name: "Cebuano", code: "ceb", direction: "ltr", shortCode: "ph" },
  { name: "Chichewa", code: "ny", direction: "ltr", shortCode: "mw" },
  {
    name: "Chinese (Simplified)",
    code: "zh-CN",
    direction: "ltr",
    shortCode: "cn",
  },
  {
    name: "Chinese (Traditional)",
    code: "zh-TW",
    direction: "ltr",
    shortCode: "tw",
  },
  { name: "Corsican", code: "co", direction: "ltr", shortCode: "fr" },
  { name: "Croatian", code: "hr", direction: "ltr", shortCode: "hr" },
  { name: "Czech", code: "cs", direction: "ltr", shortCode: "cz" },
  { name: "Danish", code: "da", direction: "ltr", shortCode: "dk" },
  { name: "Dutch", code: "nl", direction: "ltr", shortCode: "nl" },
  { name: "English", code: "en", direction: "ltr", shortCode: "gb" },
  { name: "Esperanto", code: "eo", direction: "ltr", shortCode: "n/a" },
  { name: "Estonian", code: "et", direction: "ltr", shortCode: "ee" },
  { name: "Filipino", code: "tl", direction: "ltr", shortCode: "ph" },
  { name: "Finnish", code: "fi", direction: "ltr", shortCode: "fi" },
  { name: "French", code: "fr", direction: "ltr", shortCode: "fr" },
  { name: "Frisian", code: "fy", direction: "ltr", shortCode: "nl" },
  { name: "Galician", code: "gl", direction: "ltr", shortCode: "es" },
  { name: "Georgian", code: "ka", direction: "ltr", shortCode: "ge" },
  { name: "German", code: "de", direction: "ltr", shortCode: "de" },
  { name: "Greek", code: "el", direction: "ltr", shortCode: "gr" },
  { name: "Gujarati", code: "gu", direction: "ltr", shortCode: "in" },
  { name: "Haitian Creole", code: "ht", direction: "ltr", shortCode: "ht" },
  { name: "Hausa", code: "ha", direction: "ltr", shortCode: "ng" },
  { name: "Hawaiian", code: "haw", direction: "ltr", shortCode: "us" },
  { name: "Hebrew", code: "iw", direction: "ltr", shortCode: "il" },
  { name: "Hindi", code: "hi", direction: "ltr", shortCode: "in" },
  { name: "Hmong", code: "hmn", direction: "ltr", shortCode: "la" },
  { name: "Hungarian", code: "hu", direction: "ltr", shortCode: "hu" },
  { name: "Icelandic", code: "is", direction: "ltr", shortCode: "is" },
  { name: "Igbo", code: "ig", direction: "ltr", shortCode: "ng" },
  { name: "Indonesian", code: "id", direction: "ltr", shortCode: "id" },
  { name: "Irish", code: "ga", direction: "ltr", shortCode: "ie" },
  { name: "Italian", code: "it", direction: "ltr", shortCode: "it" },
  { name: "Japanese", code: "ja", direction: "ltr", shortCode: "jp" },
  { name: "Javanese", code: "jw", direction: "ltr", shortCode: "id" },
  { name: "Kannada", code: "kn", direction: "ltr", shortCode: "in" },
  { name: "Kazakh", code: "kk", direction: "ltr", shortCode: "kz" },
  { name: "Khmer", code: "km", direction: "ltr", shortCode: "kh" },
  { name: "Kinyarwanda", code: "rw", direction: "ltr", shortCode: "rw" },
  { name: "Korean", code: "ko", direction: "ltr", shortCode: "kr" },
  { name: "Kurdish (Kurmanji)", code: "ku", direction: "ltr", shortCode: "tr" },
  { name: "Kyrgyz", code: "ky", direction: "ltr", shortCode: "kg" },
  { name: "Lao", code: "lo", direction: "ltr", shortCode: "la" },
  { name: "Latin", code: "la", direction: "ltr", shortCode: "n/a" },
  { name: "Latvian", code: "lv", direction: "ltr", shortCode: "lv" },
  { name: "Lithuanian", code: "lt", direction: "ltr", shortCode: "lt" },
  { name: "Luxembourgish", code: "lb", direction: "ltr", shortCode: "lu" },
  { name: "Macedonian", code: "mk", direction: "ltr", shortCode: "mk" },
  { name: "Malagasy", code: "mg", direction: "ltr", shortCode: "mg" },
  { name: "Malay", code: "ms", direction: "ltr", shortCode: "my" },
  { name: "Malayalam", code: "ml", direction: "ltr", shortCode: "in" },
  { name: "Maltese", code: "mt", direction: "ltr", shortCode: "mt" },
  { name: "Maori", code: "mi", direction: "ltr", shortCode: "nz" },
  { name: "Marathi", code: "mr", direction: "ltr", shortCode: "in" },
  { name: "Mongolian", code: "mn", direction: "ltr", shortCode: "mn" },
  { name: "Myanmar (Burmese)", code: "my", direction: "ltr", shortCode: "mm" },
  { name: "Nepali", code: "ne", direction: "ltr", shortCode: "np" },
  { name: "Norwegian", code: "no", direction: "ltr", shortCode: "no" },
  { name: "Odia (Oriya)", code: "or", direction: "ltr", shortCode: "in" },
  { name: "Pashto", code: "ps", direction: "ltr", shortCode: "af" },
  { name: "Persian", code: "fa", direction: "ltr", shortCode: "ir" },
  { name: "Polish", code: "pl", direction: "ltr", shortCode: "pl" },
  { name: "Portuguese", code: "pt", direction: "ltr", shortCode: "pt" },
  { name: "Punjabi", code: "pa", direction: "ltr", shortCode: "in" },
  { name: "Romanian", code: "ro", direction: "ltr", shortCode: "ro" },
  { name: "Russian", code: "ru", direction: "ltr", shortCode: "ru" },
  { name: "Samoan", code: "sm", direction: "ltr", shortCode: "ws" },
  { name: "Scots Gaelic", code: "gd", direction: "ltr", shortCode: "gb" },
  { name: "Serbian", code: "sr", direction: "ltr", shortCode: "rs" },
  { name: "Sesotho", code: "st", direction: "ltr", shortCode: "ls" },
  { name: "Shona", code: "sn", direction: "ltr", shortCode: "zw" },
  { name: "Sindhi", code: "sd", direction: "ltr", shortCode: "pk" },
  { name: "Sinhala", code: "si", direction: "ltr", shortCode: "lk" },
  { name: "Slovak", code: "sk", direction: "ltr", shortCode: "sk" },
  { name: "Slovenian", code: "sl", direction: "ltr", shortCode: "si" },
  { name: "Somali", code: "so", direction: "ltr", shortCode: "so" },
  { name: "Español", code: "es", direction: "ltr", shortCode: "es" },
  { name: "Sundanese", code: "su", direction: "ltr", shortCode: "id" },
  { name: "Swahili", code: "sw", direction: "ltr", shortCode: "ke" },
  { name: "Swedish", code: "sv", direction: "ltr", shortCode: "se" },
  { name: "Tajik", code: "tg", direction: "ltr", shortCode: "tj" },
  { name: "Tamil", code: "ta", direction: "ltr", shortCode: "in" },
  { name: "Tatar", code: "tt", direction: "ltr", shortCode: "ru" },
  { name: "Telugu", code: "te", direction: "ltr", shortCode: "in" },
  { name: "Thai", code: "th", direction: "ltr", shortCode: "th" },
  { name: "Turkish", code: "tr", direction: "ltr", shortCode: "tr" },
  { name: "Turkmen", code: "tk", direction: "ltr", shortCode: "tm" },
  { name: "Ukrainian", code: "uk", direction: "ltr", shortCode: "ua" },
  { name: "Urdu", code: "ur", direction: "rtl", shortCode: "pk" },
  { name: "Uyghur", code: "ug", direction: "ltr", shortCode: "cn" },
  { name: "Uzbek", code: "uz", direction: "ltr", shortCode: "uz" },
  { name: "Vietnamese", code: "vi", direction: "ltr", shortCode: "vn" },
  { name: "Welsh", code: "cy", direction: "ltr", shortCode: "gb" },
  { name: "Xhosa", code: "xh", direction: "ltr", shortCode: "za" },
  { name: "Yiddish", code: "yi", direction: "ltr", shortCode: "il" },
  { name: "Yoruba", code: "yo", direction: "ltr", shortCode: "ng" },
  { name: "Zulu", code: "zu", direction: "ltr", shortCode: "za" },
];

export default languages;
