import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AuthBootstrap from '@/components/auth/AuthBootstrap';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Snap AI - AI Powered Image Builder',
  description: 'Generated by ai-dev',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthBootstrap />
        {children}
      </body>
    </html>
  );
}
