import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { cookies } from 'next/headers';

import AuthBootstrap from '@/components/auth/AuthBootstrap';
import {
  ACCESS_TOKEN_COOKIE_NAME,
  REFRESH_TOKEN_COOKIE_NAME,
} from '@/lib/auth/cookies';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Snap AI - AI Powered Image Builder',
  description: 'Generated by ai-dev',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasAccessToken = cookieStore.has(ACCESS_TOKEN_COOKIE_NAME);
  const hasRefreshToken = cookieStore.has(REFRESH_TOKEN_COOKIE_NAME);

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthBootstrap
          hasAnyAuthCookie={hasAccessToken || hasRefreshToken}
          hasRefreshToken={hasRefreshToken}
        />
        {children}
      </body>
    </html>
  );
}
